config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'

  get 'home/about' => 'homes#about'
  
  get 'home/search' => 'homes#search', as: 'search'
  
  get 'searchs/search' => 'searchs#search'

  resources :users, only: [:show, :index, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
  end

  resources :books, only: [:show, :index, :edit, :create, :update] do
    resources :favorites, only: [:create,]
    delete 'favorites' => 'favorites#destroy', as:'favorite'
    resources :comments, only: [:create, :destroy]
  end
  
  

  delete 'books/:id' => 'books#destroy', as:'destroy_book'
  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord


  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def Book.search(search_word)
    Book.where(['category LIKE ?', "#{search_word}"])
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { in: 2..20}, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
  
  
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  
  
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower_user, through: :followed, source: :follower
  
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    following_user.include?(user)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all.order(params[:sort])
  end

  def show
    @booki = Book.find(params[:id])
    @book = Book.new
    @user = @booki.user
    @comment = Comment.new
  end
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book)
    else
       render :edit
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

 private

 def book_params
   params.require(:book).permit(:title, :body, :evaluation, :category)
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

    @booki = Book.find(params[:book_id])
    comment = current_user.comments.new(comment_params)
    comment.book_id = @booki.id
    comment.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @booki = Book.find(params[:book_id])
    comment = Comment.find(params[:id])
     #comment = current_user.comments.find_by(id: @booki.id)
   
    comment.destroy
    # redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


  def create
    @booki = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @booki.id)
    @favorite.save
    # @favorite = Favorite.create(user_id: current_user.id, book_id: @booki.id)
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @booki = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @booki.id)
    @favorite.destroy
    # redirect_back(fallback_location: root_path)
  end





end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def search
    @user = current_user
    @book = Book.new
    @books = Book.search(params[:keyword])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_back(fallback_location: root_path)
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.following_user
  end
  
  def followers
    user = User.find(params[:user_id])
    @users = user.follower_user
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @value = params["value"]
    @model = params["model"]
    @method = params["method"]
    @dates = search_for(@method, @model, @value)
  end
  
  

private

def search_for(method, model, value)
  case method
  when 'match'
    match(model, value)
  when 'forward'
    forward(model, value)
  when 'backward'
    backward(model, value)
  when 'partical'
    partical(model, value)
  end
end





def match(model, value)
  if model == 'user'
    User.where(name: value)
  elsif model == 'book'
    Book.where(title: value)
  end
end

def forward(model, value)
  if model == 'user'
    User.where("name LIKE ?", "#{value}%")
  elsif model == 'book'
    Book.where("title LIKE ?", "#{value}%")
  end
end

def backward(model, value)
  if model == 'user'
    User.where("name LIKE ?", "%#{value}")
  elsif model == 'book'
    Book.where("title LIKE ?", "%#{value}")
  end
end

def partical(model, value)
  if model == 'user'
    User.where("name LIKE ?", "%#{value}%")
  elsif model == 'book'
    Book.where("title LIKE ?", "%#{value}%")
  end
end









end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.order(:created_at)
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </table>
        <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
        <span class="fas fa-user-cog"></span>
        <% end %>
        <h2>New book</h2>
        <%= form_with model:book, local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class:"form-control" %>
        <p>Opinion</p>
        <%= f.text_area :body, class:"form-control" %>
        <p>Category</p>
        <%= f.text_field :category, class:"form-control" %>
        <br>
        <div id="evaluation_stars" class="mb-2">
          <%= f.label :evaluation,'Rate'  %>
        </div>
        <script>
          $('#evaluation_stars').raty({
            size     : 36,
            starOn: '<%= asset_path('star-on.png') %>',
            starOff: '<%= asset_path('star-off.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'book[evaluation]',
            half: true,
          });
        </script>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
        

app/views/books/category.html.erb
<body>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
      <% if @book.errors.any? %>
       <div class="error">
       <%= @book.errors.count %>error prohibited this obj from being saved:
       <ul>
       <% @book.errors.full_messages.each do |message| %>
        <%= message %>
       <% end %>
       </ul>
       </div>
      <% end %>

      <%= render 'books/list', book: @book, user: @user %>

      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <%= link_to "新しい順", books_path(sort: '[created_at] desc') %> | <%= link_to "評価の高い順", books_path(sort: '[evaluation] desc') %>
        <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th colspan="3"></th>
            <th></th>
           </tr>
          </thead>
          <tbody>
           <% @books.each do |book| %>
           <tr>
             <th>
               <%= link_to user_path(book.user) do %>
               <%= attachment_image_tag book.user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               <% end %>
               </th>
             <th><%= link_to book.title, book_path(book.id) %></th>
             <th><%= book.body %></th>
             <th><%= book.category %></th>
             <th class="book_<%= book.id %>">
                 <%= render 'favorites/favorite2-button', booki: book %>
             </th>
             <th><p>コメント数：<%= book.comments.count %></p></th>
             <th>
                <div id="evaluation-rate-index<%= book.id %>">
                </div>
                <script>
                  $('#evaluation-rate-index<%= book.id %>').raty({
                    size     : 36,
                    starOn: '<%= asset_path('star-on.png') %>',
                    starOff: '<%= asset_path('star-off.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    score: <%= book.evaluation %>,
                    half: true,
                    readOnly: true,
                  });
                </script>
            </th>
           </tr>
           <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</body>

app/views/books/index.html.erb
<body>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
      <% if @book.errors.any? %>
       <div class="error">
       <%= @book.errors.count %>error prohibited this obj from being saved:
       <ul>
       <% @book.errors.full_messages.each do |message| %>
        <%= message %>
       <% end %>
       </ul>
       </div>
      <% end %>

      <%= render 'books/list', book: @book, user: @user %>

      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <%= link_to "新しい順", books_path(sort: '[created_at] desc') %> | <%= link_to "評価の高い順", books_path(sort: '[evaluation] desc') %>
        
        
        
  
        <div class="overflow-auto" style="width:100%; height:700px">
        <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th colspan="3"></th>
            <th></th>
           </tr>
          </thead>
          <tbody>
           <% @books.each do |book| %>
           <tr>
             <th>
               <%= link_to user_path(book.user) do %>
               <%= attachment_image_tag book.user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               <% end %>
               </th>
             <th><%= link_to book.title, book_path(book.id) %></th>
             <th><%= book.body %></th>
             <th><%= link_to book.category, search_path(keyword: book.category) %></th>
             <th class="book_<%= book.id %>">
                 <%= render 'favorites/favorite2-button', booki: book %>
             </th>
             <th><p>コメント数：<%= book.comments.count %></p></th>
             <th>
                <div id="evaluation-rate-index<%= book.id %>">
                </div>
                <script>
                  $('#evaluation-rate-index<%= book.id %>').raty({
                    size     : 36,
                    starOn: '<%= asset_path('star-on.png') %>',
                    starOff: '<%= asset_path('star-off.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    score: <%= book.evaluation %>,
                    half: true,
                    readOnly: true,
                  });
                </script>
            </th>
           </tr>
           <% end %>
          </tbody>
        </table>
        </div>

        
        
      </div>
    </div>
  </div>
</body>

app/views/books/show.html.erb
<body>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', book: @book, user: @user %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          
           <tr>
            <th><%= link_to user_path(@booki.user) do %>
               <%= attachment_image_tag @booki.user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               <% end %><br>
               <%= link_to @user.name, user_path(@booki.user) %>
               </th>
            <th><%= link_to @booki.title, book_path(@booki.id) %></th>
            <th><%= @booki.body %></th>
            <th><%= link_to @booki.category, search_path(keyword: @book.category) %></th>
            <th class="book_<%= @booki.id %>">
              <%= render 'favorites/favorite-button', booki: @booki %>
            </th>
            <th class="comment-view">
                <p>コメント件数：<%= @booki.comments.count %></p>
            </th>
            <th>
                <div id="evaluation-rate<%= @booki.id %>">
                </div>
                <script>
                  $('#evaluation-rate<%= @booki.id %>').raty({
                    size     : 36,
                    starOn: '<%= asset_path('star-on.png') %>',
                    starOff: '<%= asset_path('star-off.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    score: <%= @booki.evaluation %>,
                    half: true,
                    readOnly: true,
                  });
                </script>
            </th>
            <% if @booki.user == current_user %>
            <th><%= link_to "Edit", edit_book_path(@booki) ,class:"btn btn-sm btn-success" %></th>
            <th><%= link_to "Destroy", destroy_book_path(@booki) , method: :delete , "data-confirm" => "本当に消しますか？" ,class:"btn btn-sm btn-danger" %></th>
            <% end %>



            


           </tr>
        </table>
        
        
         <table>
          <tbody id="comment_area">
            <%= render 'comments/comment', booki: @booki %>
          </tbody>
        </table>

        
        <div class="new-comment" >
            <%= form_with(model:[@booki, @comment], remote:true) do |f| %>
            <%= f.text_area :comment, size:"80x6", class:"inputComment" %><br>
            <%= f.submit "送信" %>
            <% end %>
        </div>
      </div>

    </div>
  </div>
</body>

app/views/comments/_comment.html.erb
<% booki.comments.each do |comment| %>
 <tr>
    <td><%= attachment_image_tag comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %><br><%= comment.user.name %></td>
    <td></td>
    <td><%= comment.comment %></td>
    <td>
      <% if comment.user == current_user %>
      <%= link_to "Destroy", book_comment_path(comment.book, comment), class:"btn btn-sm btn-danger", method: :delete, remote: true %>
      <% end %>
    </td>
 </tr>
<% end %>

app/views/comments/create.js.erb
$('#comment_area').html("<%= j( render 'comments/comment', booki: @booki ) %>")
$(".inputComment").val('');
$(".comment-view").html( "コメント件数：<%= @booki.comments.count %>" );

app/views/comments/destroy.js.erb
$('#comment_area').html("<%= j( render 'comments/comment', booki: @booki ) %>")
$(".comment-view").html( "コメント件数：<%= @booki.comments.count %>" );

app/views/favorites/_favorite-button.html.erb
<% if booki.favorited_by?(current_user) %>
  <%= link_to book_favorite_path(booki), method: :delete, remote: true do %>
     <i class="fas fa-heart"></i>
  <% end %>
  <%= booki.favorites.count %>
 <% else %>
  <%= link_to book_favorites_path(booki), method: :post, remote: true do %>
   <i class="far fa-heart"></i>
  <% end %>
  <%= booki.favorites.count %>
 <% end %>

app/views/favorites/_favorite2-button.html.erb
<% if booki.favorited_by?(current_user) %>
  <%= link_to  book_favorite_path(id: booki.id, book_id: booki.id), method: :delete, remote: true do %>
     <i class="fas fa-heart"></i>
  <% end %>
  <%= booki.favorites.count %>
 <% else %>
  <%= link_to  book_favorites_path(id: booki.id, book_id: booki.id), method: :post, remote: true do %>
   <i class="far fa-heart"></i>
  <% end %>
  <%= booki.favorites.count %>
 <% end %>

app/views/favorites/create.js.erb
$(".book_<%= @booki.id %>").html("<%= j( render 'favorites/favorite-button', booki: @booki) %>");
alert('いいねできてるよ');

app/views/favorites/destroy.js.erb
$(".book_<%= @booki.id %>").html("<%= j( render 'favorites/favorite-button', booki: @booki) %>")
alert('いいね取れたね');

app/views/homes/about.html.erb
<body>
  <div class="container">
    <div class="row">
      <h1 class="px-3 py-3 mx-auto">
        Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
        </h1>
    </div>
  </div>
</body>

app/views/homes/search.html.erb
<body>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
      <% if @book.errors.any? %>
       <div class="error">
       <%= @book.errors.count %>error prohibited this obj from being saved:
       <ul>
       <% @book.errors.full_messages.each do |message| %>
        <%= message %>
       <% end %>
       </ul>
       </div>
      <% end %>

      <%= render 'books/list', book: @book, user: @user %>

      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th colspan="3"></th>
            <th></th>
           </tr>
          </thead>
          <tbody>
           <% @books.each do |book| %>
           <tr>
             <th>
               <%= link_to user_path(book.user) do %>
               <%= attachment_image_tag book.user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               <% end %>
               </th>
             <th><%= link_to book.title, book_path(book.id) %></th>
             <th><%= book.body %></th>
             <th><%= link_to book.category, search_path(keyword: book.category) %></th>
             <th class="book_<%= book.id %>">
                 <%= render 'favorites/favorite2-button', booki: book %>
             </th>
             <th><p>コメント数：<%= book.comments.count %></p></th>
             <th>
                <div id="evaluation-rate-index<%= book.id %>">
                </div>
                <script>
                  $('#evaluation-rate-index<%= book.id %>').raty({
                    size     : 36,
                    starOn: '<%= asset_path('star-on.png') %>',
                    starOff: '<%= asset_path('star-off.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    score: <%= book.evaluation %>,
                    half: true,
                    readOnly: true,
                  });
                </script>
            </th>
           </tr>
           <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</body>

app/views/users/index.html.erb
<body>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

            <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.following_user.count, user_followings_path(@user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.follower_user.count, user_followers_path(@user) %></th>
          </tr>
        </table>
        <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
        <span class="fas fa-user-cog"></span>
        <% end %>
        <h2>New book</h2>
        <%= form_with model:@book, local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %>
        <p>Category</p>
        <%= f.text_field :category %>
        <br>
        <div id="evaluation_stars" class="mt-2">
          <%= f.label :evaluation,'Rate'  %>
        </div>
        <script>
          $('#evaluation_stars').raty({
            size     : 36,
            starOn: '<%= asset_path('star-on.png') %>',
            starOff: '<%= asset_path('star-off.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'book[evaluation]',
            half: true,
          });
        </script>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>

      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-inverse">
          <thead>
           <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
            <th></th>
            <th></th>
           </tr>
          </thead>
          <tbody>
           <% @users.each do |user| %>
           <tr>
             <th>
               <%= attachment_image_tag user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               </th>
             <th><%= user.name %></th>
             <th><p>フォロー数:<%= user.following_user.count %></p></th>
             <th><p>フォロワー数:<%= user.follower_user.count %></p></th>
             <th>
               <% if user == current_user %>
               <% else %>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォローを外す", user_relationship_path(id: user.id, user_id: user.id), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(id: user.id, user_id: user.id), method: :post %>
                  <% end %>
               <% end %>
               
             </th>
             <th><%= link_to "Show", user_path(user.id) %></th>
           </tr>
           <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</body>

app/views/users/show.html.erb
<body>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.following_user.count, user_followings_path(@user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.follower_user.count, user_followers_path(@user) %></th>
          </tr>
        </table>
        <% if @user == current_user %>
          <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
          <span class="fas fa-user-cog"></span>
          <% end %>
        <% else %>
          <% if current_user.following?(@user) %>
            <%= link_to "Unfollow", user_relationship_path(@user), class:"btn btn-info", method: :delete %>
          <% else %>
            <%= link_to "Follow", user_relationships_path(@user), class:"btn btn-success",method: :post %>
          <% end %>
        <% end %>
        <h2>New book</h2>
        <%= form_with model:@book, local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %>
        <p>Category</p>
        <%= f.text_field :category %>
        <br>
        <div id="evaluation_stars" class="mt-2">
          <%= f.label :evaluation,'Rate'  %>
        </div>
        <script>
          $('#evaluation_stars').raty({
            size     : 36,
            starOn: '<%= asset_path('star-on.png') %>',
            starOff: '<%= asset_path('star-off.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'book[evaluation]',
            half: true,
          });
        </script>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th colspan="3"></th>
           </tr>
          </thead>
          <tbody>
           <% @books.each do |book| %>
           <tr>
             <th>
               <%= link_to user_path(@user) do %>
               <%= attachment_image_tag @user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               <% end %>
               </th>
             <th><%= link_to book.title, book_path(book.id) %></th>
             <th><%= book.body %></th>
             <th><%= link_to book.category, search_path(keyword: book.category) %></th>
             <th><p>コメント件数：<%= book.comments.count %></p></th>
             <th>
                <div id="evaluation-rate-usershow<%= book.id %>">
                </div>
                <script>
                  $('#evaluation-rate-usershow<%= book.id %>').raty({
                    size     : 36,
                    starOn: '<%= asset_path('star-on.png') %>',
                    starOff: '<%= asset_path('star-off.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    score: <%= book.evaluation %>,
                    half: true,
                    readOnly: true,
                  });
                </script>
            </th>
           </tr>
           <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</body>