config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'

  get 'home/about' => 'homes#about'
  
  get 'home/search' => 'homes#search', as: 'search'
  
  get 'searchs/search' => 'searchs#search'

  resources :users, only: [:show, :index, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
  end

  resources :books, only: [:show, :index, :edit, :create, :update] do
    resources :favorites, only: [:create,]
    delete 'favorites' => 'favorites#destroy', as:'favorite'
    resources :comments, only: [:create, :destroy]
  end
  
  

  delete 'books/:id' => 'books#destroy', as:'destroy_book'
  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord


  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def Book.search(search_word)
    Book.where(['category LIKE ?', "#{search_word}"])
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { in: 2..20}, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
  
  
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  
  
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower_user, through: :followed, source: :follower
  
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    following_user.include?(user)
  end
  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all.order(params[:sort])
  end

  def show
    @booki = Book.find(params[:id])
    @book = Book.new
    @user = @booki.user
    @comment = Comment.new
  end
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book)
    else
       render :edit
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

 private

 def book_params
   params.require(:book).permit(:title, :body, :evaluation, :category)
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

    @booki = Book.find(params[:book_id])
    comment = current_user.comments.new(comment_params)
    comment.book_id = @booki.id
    comment.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @booki = Book.find(params[:book_id])
    comment = Comment.find(params[:id])
     #comment = current_user.comments.find_by(id: @booki.id)
   
    comment.destroy
    # redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


  def create
    @booki = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @booki.id)
    @favorite.save
    # @favorite = Favorite.create(user_id: current_user.id, book_id: @booki.id)
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @booki = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @booki.id)
    @favorite.destroy
    # redirect_back(fallback_location: root_path)
  end





end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def search
    @user = current_user
    @book = Book.new
    @books = Book.search(params[:keyword])
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @value = params["value"]
    @model = params["model"]
    @method = params["method"]
    @dates = search_for(@method, @model, @value)
  end
  
  

private

def search_for(method, model, value)
  case method
  when 'match'
    match(model, value)
  when 'forward'
    forward(model, value)
  when 'backward'
    backward(model, value)
  when 'partical'
    partical(model, value)
  end
end





def match(model, value)
  if model == 'user'
    User.where(name: value)
  elsif model == 'book'
    Book.where(title: value)
  end
end

def forward(model, value)
  if model == 'user'
    User.where("name LIKE ?", "#{value}%")
  elsif model == 'book'
    Book.where("title LIKE ?", "#{value}%")
  end
end

def backward(model, value)
  if model == 'user'
    User.where("name LIKE ?", "%#{value}")
  elsif model == 'book'
    Book.where("title LIKE ?", "%#{value}")
  end
end

def partical(model, value)
  if model == 'user'
    User.where("name LIKE ?", "%#{value}%")
  elsif model == 'book'
    Book.where("title LIKE ?", "%#{value}%")
  end
end









end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.order(:created_at)
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
        <div class="container">
          <a class="navbar-brand" href="">
            <span>Bookers</span>
          </a>
          <div>
           <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class:"nav-link" do %>
              <span class="fas fa-home text-light"  > Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class:"nav-link" do %>
              <span class="fas fa-users text-light" > Users</span>
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class:"nav-link" do %>
              <span class="fas fa-book-open text-light"> Books</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path , method: :delete, class:"nav-link" do %>
              <span class="fas fa-sign-out-alt text-light"> logout</span>
              <% end %>
            </li>
            <li>
              <%= form_with url:search_path, method: :get, local:true do |f| %>
              <%= f.text_field :keyword %>
              <%= f.submit "検索" %>
              <% end %>
            </li>
      
            <% else %>
            <li>
              <%= link_to root_path, class:"nav-link" do %>
              <span class="fas fa-home text-light"> Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path, class:"nav-link" do %>
              <span class="fas fa-link text-light"> About</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class:"nav-link" do %>
              <span class="fas fa-user-plus text-light"> sign up</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class:"nav-link" do %>
              <span class="fas fa-sign-in-alt text-light"> login</span>
              <% end %>
            </li>
            <% end %>
           </ul>
          </div>
        </div>
      </nav>
      
      <% if user_signed_in? %>
      
      <div class="row">
        <div class="col-8 col-offset-4 text-right">
          
        </div>
      </div>

      <% end %>
    </header>
    <p class="notice"><%= notice %></p>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>